module.exports = {
  // CATEGORY
  CATEGORY_FOLDER: "category",
  CATEGORY_THUMB_WIDTH: 200,
  CATEGORY_THUMB_HEIGHT: 200,
  // PRODUCT
  PRODUCT_FOLDER: "product",
  PRODUCT_THUMB_WIDTH: 200,
  PRODUCT_THUMB_HEIGHT: 200,
  // COMPANY
  COMPANY_FOLDER: "company",
  // BRAND
  BRAND_FOLDER: "brand",
  BRAND_THUMB_WIDTH: 200,
  BRAND_THUMB_HEIGHT: 200,
  // SETTING
  SETTING_FOLDER: "setting",
  // USER
  USER_FOLDER: "user",
  USER_THUMB_WIDTH: 200,
  USER_THUMB_HEIGHT: 200,
  // Home
  HOME_FOLDER: "home",
  HOME_THUMB_WIDTH: 200,
  HOME_THUMB_HEIGHT: 200,

  PRODUCT_IMPORT_FOLDER: "product_imports",
  INVENTORY_IMPORT_FOLDER: "inventories_import",
  CATEGORY_IMPORT_FOLDER: "categories_import",
};
