const countries = [
    {name: "Afghanistan",code: "AF",symbol: "؋",currency: "AFN"},
    {name: "Aland Islands",code: "AX",symbol: "€",currency: "EUR"},
    {name: "Albania",code: "AL",symbol: "Lek",currency: "ALL"},
    {name: "Algeria",code: "DZ",symbol: "دج",currency: "DZD"},
    {name: "American Samoa",code: "AS",symbol: "$",currency: "USD"},
    {name: "Andorra",code: "AD",symbol: "€",currency: "EUR"},
    {name: "Angola",code: "AO",symbol: "Kz",currency: "AOA"},
    {name: "Anguilla",code: "AI",symbol: "$",currency: "XCD"},
    {name: "Antarctica",code: "AQ",symbol: "$",currency: "AAD"},
    {name: "Antigua and Barbuda",code: "AG",symbol: "$",currency: "XCD"},
    {name: "Argentina",code: "AR",symbol: "$",currency: "ARS"},
    {name: "Armenia",code: "AM",symbol: "֏",currency: "AMD"},
    {name: "Aruba",code: "AW",symbol: "ƒ",currency: "AWG"},
    {name: "Australia",code: "AU",symbol: "$",currency: "AUD"},
    {name: "Austria",code: "AT",symbol: "€",currency: "EUR"},
    {name: "Azerbaijan",code: "AZ",symbol: "m",currency: "AZN"},
    {name: "Bahamas",code: "BS",symbol: "B$",currency: "BSD"},
    {name: "Bahrain",code: "BH",symbol: ".د.ب",currency: "BHD"},
    {name: "Bangladesh",code: "BD",symbol: "৳",currency: "BDT"},
    {name: "Barbados",code: "BB",symbol: "Bds$",currency: "BBD"},
    {name: "Belarus",code: "BY",symbol: "Br",currency: "BYN"},
    {name: "Belgium",code: "BE",symbol: "€",currency: "EUR"},
    {name: "Belize",code: "BZ",symbol: "$",currency: "BZD"},
    {name: "Benin",code: "BJ",symbol: "CFA",currency: "XOF"},
    {name: "Bermuda",code: "BM",symbol: "$",currency: "BMD"},
    {name: "Bhutan",code: "BT",symbol: "Nu.",currency: "BTN"},
    {name: "Bolivia",code: "BO",symbol: "Bs.",currency: "BOB"},
    {name: "Bonaire, Sint Eustatius and Saba",code: "BQ",symbol: "$",currency: "USD"},
    {name: "Bosnia and Herzegovina",code: "BA",symbol: "KM",currency: "BAM"},
    {name: "Botswana",code: "BW",symbol: "P",currency: "BWP"},
    {name: "Bouvet Island",code: "BV",symbol: "kr",currency: "NOK"},
    {name: "Brazil",code: "BR",symbol: "R$",currency: "BRL"},
    {name: "British Indian Ocean Territory",code: "IO",symbol: "$",currency: "USD"},
    {name: "Brunei Darussalam",code: "BN",symbol: "B$",currency: "BND"},
    {name: "Bulgaria",code: "BG",symbol: "Лв.",currency: "BGN"},
    {name: "Burkina Faso",code: "BF",symbol: "CFA",currency: "XOF"},
    {name: "Burundi",code: "BI",symbol: "FBu",currency: "BIF"},
    {name: "Cambodia",code: "KH",symbol: "KHR",currency: "KHR"},
    {name: "Cameroon",code: "CM",symbol: "FCFA",currency: "XAF"},
    {name: "Canada",code: "CA",symbol: "$",currency: "CAD"},
    {name: "Cape Verde",code: "CV",symbol: "$",currency: "CVE"},
    {name: "Cayman Islands",code: "KY",symbol: "$",currency: "KYD"},
    {name: "Central African Republic",code: "CF",symbol: "FCFA",currency: "XAF"},
    {name: "Chad",code: "TD",symbol: "FCFA",currency: "XAF"},
    {name: "Chile",code: "CL",symbol: "$",currency: "CLP"},
    {name: "China",code: "CN",symbol: "¥",currency: "CNY"},
    {name: "Christmas Island",code: "CX",symbol: "$",currency: "AUD"},
    {name: "Cocos (Keeling) Islands",code: "CC",symbol: "$",currency: "AUD"},
    {name: "Colombia",code: "CO",symbol: "$",currency: "COP"},
    {name: "Comoros",code: "KM",symbol: "CF",currency: "KMF"},
    {name: "Congo",code: "CG",symbol: "FC",currency: "XAF"},
    {name: "Congo, Democratic Republic of the Congo",code: "CD",symbol: "FC",currency: "CDF"},
    {name: "Cook Islands",code: "CK",symbol: "$",currency: "NZD"},
    {name: "Costa Rica",code: "CR",symbol: "₡",currency: "CRC"},
    {name: "Cote D'Ivoire",code: "CI",symbol: "CFA",currency: "XOF"},
    {name: "Croatia",code: "HR",symbol: "kn",currency: "HRK"},
    {name: "Cuba",code: "CU",symbol: "$",currency: "CUP"},
    {name: "Curacao",code: "CW",symbol: "ƒ",currency: "ANG"},
    {name: "Cyprus",code: "CY",symbol: "€",currency: "EUR"},
    {name: "Czech Republic",code: "CZ",symbol: "Kč",currency: "CZK"},
    {name: "Denmark",code: "DK",symbol: "Kr.",currency: "DKK"},
    {name: "Djibouti",code: "DJ",symbol: "Fdj",currency: "DJF"},
    {name: "Dominica",code: "DM",symbol: "$",currency: "XCD"},
    {name: "Dominican Republic",code: "DO",symbol: "$",currency: "DOP"},
    {name: "Ecuador",code: "EC",symbol: "$",currency: "USD"},
    {name: "Egypt",code: "EG",symbol: "ج.م",currency: "EGP"},
    {name: "El Salvador",code: "SV",symbol: "$",currency: "USD"},
    {name: "Equatorial Guinea",code: "GQ",symbol: "FCFA",currency: "XAF"},
    {name: "Eritrea",code: "ER",symbol: "Nfk",currency: "ERN"},
    {name: "Estonia",code: "EE",symbol: "€",currency: "EUR"},
    {name: "Ethiopia",code: "ET",symbol: "Nkf",currency: "ETB"},
    {name: "Falkland Islands (Malvinas)",code: "FK",symbol: "£",currency: "FKP"},
    {name: "Faroe Islands",code: "FO",symbol: "Kr.",currency: "DKK"},
    {name: "Fiji",code: "FJ",symbol: "FJ$",currency: "FJD"},
    {name: "Finland",code: "FI",symbol: "€",currency: "EUR"},
    {name: "France",code: "FR",symbol: "€",currency: "EUR"},
    {name: "French Guiana",code: "GF",symbol: "€",currency: "EUR"},
    {name: "French Polynesia",code: "PF",symbol: "₣",currency: "XPF"},
    {name: "French Southern Territories",code: "TF",symbol: "€",currency: "EUR"},
    {name: "Gabon",code: "GA",symbol: "FCFA",currency: "XAF"},
    {name: "Gambia",code: "GM",symbol: "D",currency: "GMD"},
    {name: "Georgia",code: "GE",symbol: "ლ",currency: "GEL"},
    {name: "Germany",code: "DE",symbol: "€",currency: "EUR"},
    {name: "Ghana",code: "GH",symbol: "GH₵",currency: "GHS"},
    {name: "Gibraltar",code: "GI",symbol: "£",currency: "GIP"},
    {name: "Greece",code: "GR",symbol: "€",currency: "EUR"},
    {name: "Greenland",code: "GL",symbol: "Kr.",currency: "DKK"},
    {name: "Grenada",code: "GD",symbol: "$",currency: "XCD"},
    {name: "Guadeloupe",code: "GP",symbol: "€",currency: "EUR"},
    {name: "Guam",code: "GU",symbol: "$",currency: "USD"},
    {name: "Guatemala",code: "GT",symbol: "Q",currency: "GTQ"},
    {name: "Guernsey",code: "GG",symbol: "£",currency: "GBP"},
    {name: "Guinea",code: "GN",symbol: "FG",currency: "GNF"},
    {name: "Guinea-Bissau",code: "GW",symbol: "CFA",currency: "XOF"},
    {name: "Guyana",code: "GY",symbol: "$",currency: "GYD"},
    {name: "Haiti",code: "HT",symbol: "G",currency: "HTG"},
    {name: "Heard Island and McDonald Islands",code: "HM",symbol: "$",currency: "AUD"},
    {name: "Holy See (Vatican City State)",code: "VA",symbol: "€",currency: "EUR"},
    {name: "Honduras",code: "HN",symbol: "L",currency: "HNL"},
    {name: "Hong Kong",code: "HK",symbol: "$",currency: "HKD"},
    {name: "Hungary",code: "HU",symbol: "Ft",currency: "HUF"},
    {name: "Iceland",code: "IS",symbol: "kr",currency: "ISK"},
    {name: "India",code: "IN",symbol: "₹",currency: "INR"},
    {name: "Indonesia",code: "ID",symbol: "Rp",currency: "IDR"},
    {name: "Iran, Islamic Republic of",code: "IR",symbol: "﷼",currency: "IRR"},
    {name: "Iraq",code: "IQ",symbol: "د.ع",currency: "IQD"},
    {name: "Ireland",code: "IE",symbol: "€",currency: "EUR"},
    {name: "Isle of Man",code: "IM",symbol: "£",currency: "GBP"},
    {name: "Israel",code: "IL",symbol: "₪",currency: "ILS"},
    {name: "Italy",code: "IT",symbol: "€",currency: "EUR"},
    {name: "Jamaica",code: "JM",symbol: "J$",currency: "JMD"},
    {name: "Japan",code: "JP",symbol: "¥",currency: "JPY"},
    {name: "Jersey",code: "JE",symbol: "£",currency: "GBP"},
    {name: "Jordan",code: "JO",symbol: "ا.د",currency: "JOD"},
    {name: "Kazakhstan",code: "KZ",symbol: "лв",currency: "KZT"},
    {name: "Kenya",code: "KE",symbol: "KSh",currency: "KES"},
    {name: "Kiribati",code: "KI",symbol: "$",currency: "AUD"},
    {name: "Korea, Democratic People's Republic of",code: "KP",symbol: "₩",currency: "KPW"},
    {name: "Korea, Republic of",code: "KR",symbol: "₩",currency: "KRW"},
    {name: "Kosovo",code: "XK",symbol: "€",currency: "EUR"},
    {name: "Kuwait",code: "KW",symbol: "ك.د",currency: "KWD"},
    {name: "Kyrgyzstan",code: "KG",symbol: "лв",currency: "KGS"},
    {name: "Lao People's Democratic Republic",code: "LA",symbol: "₭",currency: "LAK"},
    {name: "Latvia",code: "LV",symbol: "€",currency: "EUR"},
    {name: "Lebanon",code: "LB",symbol: "£",currency: "LBP"},
    {name: "Lesotho",code: "LS",symbol: "L",currency: "LSL"},
    {name: "Liberia",code: "LR",symbol: "$",currency: "LRD"},
    {name: "Libyan Arab Jamahiriya",code: "LY",symbol: "د.ل",currency: "LYD"},
    {name: "Liechtenstein",code: "LI",symbol: "CHf",currency: "CHF"},
    {name: "Lithuania",code: "LT",symbol: "€",currency: "EUR"},
    {name: "Luxembourg",code: "LU",symbol: "€",currency: "EUR"},
    {name: "Macao",code: "MO",symbol: "$",currency: "MOP"},
    {name: "Macedonia, the Former Yugoslav Republic of",code: "MK",symbol: "ден",currency: "MKD"},
    {name: "Madagascar",code: "MG",symbol: "Ar",currency: "MGA"},
    {name: "Malawi",code: "MW",symbol: "MK",currency: "MWK"},
    {name: "Malaysia",code: "MY",symbol: "RM",currency: "MYR"},
    {name: "Maldives",code: "MV",symbol: "Rf",currency: "MVR"},
    {name: "Mali",code: "ML",symbol: "CFA",currency: "XOF"},
    {name: "Malta",code: "MT",symbol: "€",currency: "EUR"},
    {name: "Marshall Islands",code: "MH",symbol: "$",currency: "USD"},
    {name: "Martinique",code: "MQ",symbol: "€",currency: "EUR"},
    {name: "Mauritania",code: "MR",symbol: "MRU",currency: "MRO"},
    {name: "Mauritius",code: "MU",symbol: "₨",currency: "MUR"},
    {name: "Mayotte",code: "YT",symbol: "€",currency: "EUR"},
    {name: "Mexico",code: "MX",symbol: "$",currency: "MXN"},
    {name: "Micronesia, Federated States of",code: "FM",symbol: "$",currency: "USD"},
    {name: "Moldova, Republic of",code: "MD",symbol: "L",currency: "MDL"},
    {name: "Monaco",code: "MC",symbol: "€",currency: "EUR"},
    {name: "Mongolia",code: "MN",symbol: "₮",currency: "MNT"},
    {name: "Montenegro",code: "ME",symbol: "€",currency: "EUR"},
    {name: "Montserrat",code: "MS",symbol: "$",currency: "XCD"},
    {name: "Morocco",code: "MA",symbol: "DH",currency: "MAD"},
    {name: "Mozambique",code: "MZ",symbol: "MT",currency: "MZN"},
    {name: "Myanmar",code: "MM",symbol: "K",currency: "MMK"},
    {name: "Namibia",code: "NA",symbol: "$",currency: "NAD"},
    {name: "Nauru",code: "NR",symbol: "$",currency: "AUD"},
    {name: "Nepal",code: "NP",symbol: "₨",currency: "NPR"},
    {name: "Netherlands",code: "NL",symbol: "€",currency: "EUR"},
    {name: "Netherlands Antilles",code: "AN",symbol: "NAf",currency: "ANG"},
    {name: "New Caledonia",code: "NC",symbol: "₣",currency: "XPF"},
    {name: "New Zealand",code: "NZ",symbol: "$",currency: "NZD"},
    {name: "Nicaragua",code: "NI",symbol: "C$",currency: "NIO"},
    {name: "Niger",code: "NE",symbol: "CFA",currency: "XOF"},
    {name: "Nigeria",code: "NG",symbol: "₦",currency: "NGN"},
    {name: "Niue",code: "NU",symbol: "$",currency: "NZD"},
    {name: "Norfolk Island",code: "NF",symbol: "$",currency: "AUD"},
    {name: "Northern Mariana Islands",code: "MP",symbol: "$",currency: "USD"},
    {name: "Norway",code: "NO",symbol: "kr",currency: "NOK"},
    {name: "Oman",code: "OM",symbol: ".ع.ر",currency: "OMR"},
    {name: "Pakistan",code: "PK",symbol: "₨",currency: "PKR"},
    {name: "Palau",code: "PW",symbol: "$",currency: "USD"},
    {name: "Palestinian Territory, Occupied",code: "PS",symbol: "₪",currency: "ILS"},
    {name: "Panama",code: "PA",symbol: "B/.",currency: "PAB"},
    {name: "Papua New Guinea",code: "PG",symbol: "K",currency: "PGK"},
    {name: "Paraguay",code: "PY",symbol: "₲",currency: "PYG"},
    {name: "Peru",code: "PE",symbol: "S/.",currency: "PEN"},
    {name: "Philippines",code: "PH",symbol: "₱",currency: "PHP"},
    {name: "Pitcairn",code: "PN",symbol: "$",currency: "NZD"},
    {name: "Poland",code: "PL",symbol: "zł",currency: "PLN"},
    {name: "Portugal",code: "PT",symbol: "€",currency: "EUR"},
    {name: "Puerto Rico",code: "PR",symbol: "$",currency: "USD"},
    {name: "Qatar",code: "QA",symbol: "ق.ر",currency: "QAR"},
    {name: "Reunion",code: "RE",symbol: "€",currency: "EUR"},
    {name: "Romania",code: "RO",symbol: "lei",currency: "RON"},
    {name: "Russian Federation",code: "RU",symbol: "₽",currency: "RUB"},
    {name: "Rwanda",code: "RW",symbol: "FRw",currency: "RWF"},
    {name: "Saint Barthelemy",code: "BL",symbol: "€",currency: "EUR"},
    {name: "Saint Helena",code: "SH",symbol: "£",currency: "SHP"},
    {name: "Saint Kitts and Nevis",code: "KN",symbol: "$",currency: "XCD"},
    {name: "Saint Lucia",code: "LC",symbol: "$",currency: "XCD"},
    {name: "Saint Martin",code: "MF",symbol: "€",currency: "EUR"},
    {name: "Saint Pierre and Miquelon",code: "PM",symbol: "€",currency: "EUR"},
    {name: "Saint Vincent and the Grenadines",code: "VC",symbol: "$",currency: "XCD"},
    {name: "Samoa",code: "WS",symbol: "SAT",currency: "WST"},
    {name: "San Marino",code: "SM",symbol: "€",currency: "EUR"},
    {name: "Sao Tome and Principe",code: "ST",symbol: "Db",currency: "STD"},
    {name: "Saudi Arabia",code: "SA",symbol: "﷼",currency: "SAR"},
    {name: "Senegal",code: "SN",symbol: "CFA",currency: "XOF"},
    {name: "Serbia",code: "RS",symbol: "din",currency: "RSD"},
    {name: "Serbia and Montenegro",code: "CS",symbol: "din",currency: "RSD"},
    {name: "Seychelles",code: "SC",symbol: "SRe",currency: "SCR"},
    {name: "Sierra Leone",code: "SL",symbol: "Le",currency: "SLL"},
    {name: "Singapore",code: "SG",symbol: "$",currency: "SGD"},
    {name: "St Martin",code: "SX",symbol: "ƒ",currency: "ANG"},
    {name: "Slovakia",code: "SK",symbol: "€",currency: "EUR"},
    {name: "Slovenia",code: "SI",symbol: "€",currency: "EUR"},
    {name: "Solomon Islands",code: "SB",symbol: "Si$",currency: "SBD"},
    {name: "Somalia",code: "SO",symbol: "Sh.so.",currency: "SOS"},
    {name: "South Africa",code: "ZA",symbol: "R",currency: "ZAR"},
    {name: "South Georgia and the South Sandwich Islands",code: "GS",symbol: "£",currency: "GBP"},
    {name: "South Sudan",code: "SS",symbol: "£",currency: "SSP"},
    {name: "Spain",code: "ES",symbol: "€",currency: "EUR"},
    {name: "Sri Lanka",code: "LK",symbol: "Rs",currency: "LKR"},
    {name: "Sudan",code: "SD",symbol: ".س.ج",currency: "SDG"},
    {name: "Suriname",code: "SR",symbol: "$",currency: "SRD"},
    {name: "Svalbard and Jan Mayen",code: "SJ",symbol: "kr",currency: "NOK"},
    {name: "Swaziland",code: "SZ",symbol: "E",currency: "SZL"},
    {name: "Sweden",code: "SE",symbol: "kr",currency: "SEK"},
    {name: "Switzerland",code: "CH",symbol: "CHf",currency: "CHF"},
    {name: "Syrian Arab Republic",code: "SY",symbol: "LS",currency: "SYP"},
    {name: "Taiwan, Province of China",code: "TW",symbol: "$",currency: "TWD"},
    {name: "Tajikistan",code: "TJ",symbol: "SM",currency: "TJS"},
    {name: "Tanzania, United Republic of",code: "TZ",symbol: "TSh",currency: "TZS"},
    {name: "Thailand",code: "TH",symbol: "฿",currency: "THB"},
    {name: "Timor-Leste",code: "TL",symbol: "$",currency: "USD"},
    {name: "Togo",code: "TG",symbol: "CFA",currency: "XOF"},
    {name: "Tokelau",code: "TK",symbol: "$",currency: "NZD"},
    {name: "Tonga",code: "TO",symbol: "$",currency: "TOP"},
    {name: "Trinidad and Tobago",code: "TT",symbol: "$",currency: "TTD"},
    {name: "Tunisia",code: "TN",symbol: "ت.د",currency: "TND"},
    {name: "Turkey",code: "TR",symbol: "₺",currency: "TRY"},
    {name: "Turkmenistan",code: "TM",symbol: "T",currency: "TMT"},
    {name: "Turks and Caicos Islands",code: "TC",symbol: "$",currency: "USD"},
    {name: "Tuvalu",code: "TV",symbol: "$",currency: "AUD"},
    {name: "Uganda",code: "UG",symbol: "USh",currency: "UGX"},
    {name: "Ukraine",code: "UA",symbol: "₴",currency: "UAH"},
    {name: "United Arab Emirates",code: "AE",symbol: "إ.د",currency: "AED"},
    {name: "United Kingdom",code: "GB",symbol: "£",currency: "GBP"},
    {name: "United States",code: "US",symbol: "$",currency: "USD"},
    {name: "United States Minor Outlying Islands",code: "UM",symbol: "$",currency: "USD"},
    {name: "Uruguay",code: "UY",symbol: "$",currency: "UYU"},
    {name: "Uzbekistan",code: "UZ",symbol: "лв",currency: "UZS"},
    {name: "Vanuatu",code: "VU",symbol: "VT",currency: "VUV"},
    {name: "Venezuela",code: "VE",symbol: "Bs",currency: "VEF"},
    {name: "Viet Nam",code: "VN",symbol: "₫",currency: "VND"},
    {name: "Virgin Islands, British",code: "VG",symbol: "$",currency: "USD"},
    {name: "Virgin Islands, U.s.",code: "VI",symbol: "$",currency: "USD"},
    {name: "Wallis and Futuna",code: "WF",symbol: "₣",currency: "XPF"},
    {name: "Western Sahara",code: "EH",symbol: "MAD",currency: "MAD"},
    {name: "Yemen",code: "YE",symbol: "﷼",currency: "YER"},
    {name: "Zambia",code: "ZM",symbol: "ZK",currency: "ZMW"},
    {name: "Zimbabwe",code: "ZW",symbol: "$",currency: "ZWL"}
];

module.exports = countries;